[functions.admin-get-users]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.generate-category-images]
verify_jwt = false

[functions.address-autocomplete]
verify_jwt = false

[functions.route-optimize]
verify_jwt = false
